image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
<<<<<<< HEAD
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
=======
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
>>>>>>> 2a9e2a05c507cfac35ae75953a057a1175238614
